sudo: false
cache:
  directories:
  - $HOME/.gradle
language: groovy
jdk:
- openjdk7
dist: trusty
env:
  global:
  - TERM=dumb
  - MALLOC_ARENA_MAX=1
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: J+KWbE5RaZvcEibGWp2X4yR7bDKyRR0Yi+fm7Fyzs8PDpI3qJj/OqYiffgjGWPMFvGsYcH7pyhaYeFz1Z/8qcNGU6pw3/QV412WqWLO1pbWQZdrGbEgES0kpZzy/rliLBYwtuIS5DyjY3L3t4D2S2vcwZpvTWU9eqVikCC+R2eg=
  - secure: YM7rkQX1UzKuvMdjw8qCAQ0kWHJFpHZBvOoPaF3kuUUEbfFj/LgEh0xERnKyKz5QduRQipEFgpy492yJT1cb1wrH2YPt1cP+oDq9KOQr6vJB6Z/Xz0WsrgrU80rUBm4KrKXPRe/DMq/Lv3twnnB3Deub3nKSERidDW40JSnMLIE=
  - secure: X1ffz/ywsPMxaN73nH86Pr4RD7q0p0IaKI7v+5yPvX2g59LY4aJFYEl9Jt65e8+c0mkESNXxocQ1dnL4lehXBFrC4rTWhJvly4URa81clbY8l5EOTZQha/tyGXUOYyaGK409LrEcmLOGSvBTV3YsV83xhMTLhrOZ1VwI5zL6MjE=
  - secure: IuhdxpD1Q1of9F7zACAgzAukE3eqSZTVYr7WgH+YMKPwHBHQVpn9tBFdSGs2zYu2GSE5kVJI8uJdxe5nH6Qz+RR1xtGueqgxiXTtfz/bYT52YoFdzb4lmtrKDqFjJHiAkhCDRRCDne/4Jeijo0eXnZaHutJimNQhQMBkxyl00Qg=
  - secure: UAhcoZ20NWTdGAUP830TD2jFVAsr3FAeuqEL7vwI43xbX0+KNG4RVn3oNEppl9LIdaKN8tjJ9753Falb7WeeTSWbHn4LLUbz0QkCABACiXIctJSg4IrnNixCH3rGHR01ds5qElOOLtqRMWFLO4cXaav9pgUtmsCBmVo+xXXw2No=
  - secure: Q/1Dc356V+upCQZn5SZAdedEs7WdLeoCE/CKySIlicq1bC9AIGK1vwUXiwmcTJpIVvusEAdTMuZX4Zz7fVy3xzDq95D6j6HpfZach/O6XHoKQLon5+w7AHh0uv1CRSdYqKLXGW18YRDGQrK5fCovdNT0+ynGX5YAZBMnu9t2Qmk=
  - secure: HvROZ9kWW9GvKw4MZKEhsgUHQh/xSVrbOr/enq9fFX4+Cf7MGXc1ySlNHhDTV1mGdP6QTIl7CI3Xz3u9yCgXy4m3eyTgVUzeQOUAv1roiR8ajv1PleVGUOqMreejUUsFDHR1gmNR9S17hJoNZPBanB43R9tJDQVvrEUnV38Wr48=
  - secure: FYgiX7uSiQFql2bQsOfHsTypik4/hArAFMaMcm05MoXBHyb5tl3VXwo3jEBp0MYsH9iIIJ8crlLy4ylm+8XMKOq300zZk2feqQME4x2DXxlUgmfZkbnvY+iUpmLa7OoMAqUV8ardbBrXVn/gQjDH9jvVcX+Gv7KnKE2xyzI0lQY=
  - secure: SbEE24W2zMdao0ArFBHTDP7ntDJn3wmaVl/T42ahkzQUSjQiND+TXwJLhaNADJDIyLg0zmFEIKUk7g7HUMOdw5a2foZbz7BESkz4Nnuhw5O7CgJdIYL6lfLNPkOA6pc7H7D0D5J39vLk4PDqpOJxUw+sgaH2gg2F13kWFk8YZVY=
  - secure: D604qHBpW7UuFuxkhu/cqVzpEESkkipWTKyz3j75i2k+ocQXcYXSj3zDMk4Hmo/iTHszwCgXk1w/5aj+mxRVecewmXmpFk3Q63qPvJprAjcvatmxp82aBmmpPd9GHjKbyLmu6Gn3R8QtX6yAT75T9lf4Y1FMi9mVwFPOtLiSEs0=
  - secure: TNZ8oWsN+E1gkvxhyTHjguyakIWm+T9KxoZVNq+OoHv2kuyWTIbTJUtP3JVyXX+P+B9F9o+8Kkxp5jomgW0cRdjWxQebceeGlrNAzTVvvOm7tVFFxLjzjRnUPsWKfGXkIzSagvFdSgHIpinDqrtERD10pbym2ZDwqRCejCMjz0U=
  - secure: io7oNZbf/aYRn+a73x6B/8yjg27CYVVdwRobQ+vZBNwBzS31bBcC/8pMtIpsBFqSEtE8GrSM4dYtMSFSj5PasiMg6PgYG/frsbtgGmRqTBkmENfv2EIO+Ex0pgycL+hCUVtPqD9j3mwhfPWkim9vPdmpYe2BbQuTYs0spJuu6PQ=
  - secure: QAOp5FWfiedjxQV2qGUlfZqvvsaBIAL9RyE1JnrcRsnNU6YIxeNCoJlafTYrn241IPU8q+E1M4yjIZOCDnl+CRTuukbo0sNIY+Sb92jA4nb+DRVnxphc0SOrFV1R90QekSnAX+C4+PAsgRasvjNJeNJVPV3P0HzJfzV3bLSPtb4=
before_install:
  # Workaround for https://github.com/gradle/gradle/issues/2421:
  # download all Gradle distributions with openjdk8
  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew
  - ./openssl-setup.sh
matrix:
  fast_finish: true
script: JAVA_HOME=$(jdk_switcher home openjdk7) "./travis-build.sh"
install: true
notifications:
  slack:
    secure: eSyvdf/vA0KGAyiITwe7ooD6BCX94PCy7o35HSkbfUbHB5XPJq/SkqRjjIeiwrgywVph+qGBPYmzIdep4BQwH+JFEfPu0gQoNWKeGAVmJ9LeFaP4vaXWvuRugunO9zUla4JT2cfmsxKVEoTfI1NIfT15hYBMHi+8CfgFlx2zOdk=
